### PR TITLE
Change installation mode

### PR DESCRIPTION
**Pull request by Freed-Wu**
Change cp to install
Use gzip to compress man

### CODE REVIEW

**Comment by LuRsT** [comment]
Hey @Freed-Wu, thanks for the contribution. I like the use of the `$PREFIX`, but I do prefer the more verbose way of installing things originally because it's easier to read (I don't know those shorthands by heart).

Also, is gziping the man page common? It's not very big so I don't see much point in compressing it.

Could you please split it up into two commits:
- One for updating the prefix and another for gziping, alternatively, I could split it up myself and get it merged :)

**Comment by Freed-Wu** [comment]
In the linux distribution I used, all man files use gzip, however, I am not sure
all linux distributions are same.

**Comment by Freed-Wu** [comment]
@LuRsT

**Comment by LuRsT** [comment]
Hey @Freed-Wu, thanks for the reminder, I just need to test it and I can merge it :+1:

**Comment by LuRsT** [comment]
LGTM, thanks again @Freed-Wu !

**Pull request merged**
