### PR TITLE
Speed up line drawing with built-in printf

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
I see!
A word is actually not only a single character.

**Comment by LuRsT** [comment]
Hi @szepeviktor, 

Thanks for your contribution and sorry for the delay, could you expand on what your change accomplishes? How does it speed up line drawing?

**Comment by szepeviktor** [comment]
@LuRsT It avoids the while loop, uses printf.

**Comment by LuRsT** [comment]
Hi @szepeviktor , I finally had time to test it and check it, and I really like this change, it is indeed much quicker, thanks for the contribution!

**Pull request merged**
