### PR TITLE
hasit's port of LuRst/hr in Go

### PR DESCRIPTION
**Pull request by hasit**
Added my port of hr in Go to the list of Alternative `hr`s

### CODE REVIEW

**Comment by LuRsT** [comment]
Hi @hasit, thanks for your contribution! Could I just ask you to fix the typo in your commit message before I merge it?

**Comment by hasit** [comment]
Oh of course. I'm sorry, that was a 3 am commit.

**Comment by LuRsT** [comment]
No problem mate, all merged up :+1: 

Thanks!

**Comment by hasit** [comment]
:+1: 
Thank you.

**Pull request merged**
